import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ActionIcon,
  Avatar,
  Button,
  Card,
  Container,
  Divider,
  Grid,
  Indicator,
  Space,
  Text,
  Title,
  useMantineTheme,
} from "@mantine/core";
import Link from "next/link";
import BsArrowRight, { BsArrowUpRight } from "react-icons/bs";
import { Carousel } from "@mantine/carousel";
import {SiTesla} from "react-icons/si";
import { useViewportSize } from "@mantine/hooks";
import useDevice from "@/Components/hooks/useDevice";
import OurTesla from "@/Components/Index/OurTesla";
import OurCustomers from "@/Components/Index/OurCustomers";
import { useRouter } from "next/router";
import SubTitle from "@/Components/hooks/UI/SubTitle";
import HeroMobile from "@/Components/Index/HeroMobile";
import HeroDesktop from "@/Components/Index/HeroDesktop";
import TeslaBlack from "../../public/images/teslaDark.jpg";
import hexToRGBA from "@/Components/hooks/hexToRGBA";
import Blog4Index from "@/Components/Index/Blog4Index";
const inter = Inter({ subsets: ["latin"] });

export default function Home({blog, main}) {
  const { height, width } = useViewportSize();
  const device = useDevice(width);
  const theme = useMantineTheme();
  const router = useRouter();

  let cardContents = [
    {
      name: "Zážitkové jízdy",
      description: "Zažijte maximální rychlost až 290 kilometrů za hodinu",
      image: "/images/zazitkove_jizdyb.jpg",
      color: theme.colors.primary[4],
      link: "/sluzby/zazitkove-jizdy",
    },
    {
      name: "Pronájem",
      description: "Užívejte si komfortu při cestování s nabíjením zdarma",
      image: "/images/pronajemb.jpg",
      color: "#71E4D3",
      link: "/sluzby/pronajem",
    },
    {
      name: "Taxi",
      description: "Spolehněte se na klidný a bezpečný odvoz",
      image: "/images/taxib.jpg",
      color: "#E1E471",
      link: "/sluzby/taxi",
    },
    {
      name: "Akce",
      description: "Reprezentujte se s prémiovým vozem Tesla S.",
      image: "/images/akce.avif",
      color: "#8171E4",
      link: "/sluzby/akce",
    },
  ];
  let slides = [
    {
      name: "Nabíjení zdarma",
      description:
        "Nedělejte si starosti s provozem. Díky rozrůstající se síti nabíjecích stanic Tesla Supercharger se nemusíte bát o nabíjení v Česku, ani okolních státech, kde je sít ještě rozšířenější. Navíc při pronájmu naší tesly máte zajištěno nabíjení zdarma u všech nabíjecích stanic společnosti Tesla",
      img: "/images/teslaMap.png",
      color: "#19E3C5",
    },
    {
      name: "Místo pro vše",
      description:
        "Vezměte na výlet celou rodinu. Přes sportovní ladění vozu je Tesla S též vhodným autem pro cestování za zážitky. Do kufru s objemem 722 litrů se vejdou nejen zavazadla ale i kola, lyže či jiné sportovní doplňky.",
      img: "/images/teslaKufr.png",
      color: "#19BFE3",
    },
    {
      name: "Klidná jízda",
      description:
        "Za vašeho dozoru umožňuje Autopilot vozu v rámci vašeho pruhu automaticky řídit, zrychlovat a brzdit. Pomáhá vám tak s nejnáročnější částí řízení. S over-the-air aktualizacemi jsou nejnovější funkce okamžitě k dispozici.",
      img: "/images/teslaKlid.png",
      color: "#DFE319",
    },
    {
      name: "Bezpečí na prvním místě",
      description:
        "Bezpečnost je nejdůležitější u každého vozu Tesla. Tesla S je navržena tak, aby překračovaly bezpečnostní standardy. Model S získal v roce 2022 5 hvězdiček v hodnocení bezpečnosti Euro NCAP a získal ocenění Nejlepší ve své třídě v kategoriích Executive a Pure Electric.",
      img: "/images/teslaSafe.png",
      color: "#E3AA19",
    },
  ];


  return (
    <>
      <Head>
        <title>Jirkova tesla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      {device !== "l" ? <HeroMobile/> : <HeroDesktop />}
    {device !== "l" ?    
    <section
        style={{
          padding: "5vh 10vw",
          display: "flex",
          flexDirection: "column",
          gap: "4vh",
          alignItems: "flex-start",
        }}
      >
        <SubTitle href={"/o-nas"} device={device} label={"O NÁS"}>Kdo jsme</SubTitle>
        <Text sx={{ fontSize: "1rem", lineHeight: "175%" }}>
          Jsme nadšenci do rychlých aut a inovací. Baví nás rychle jezdit na
          okruhu i si užívat klidné jízdy v příjemném interiéru luxusních aut.
          Chceme tento zážitek poskytnout i vám a proto vám nabízíme naše služby
          na vaší cestě.
        </Text>
        <Link href={"/o-nas"}>
          <Button
            size="lg"
            rightIcon="->"
            variant="white"
            sx={{
              paddingLeft: "0",
              color: theme.colors.neutral[7],
              fontWeight: "700",
              fontSize: "1.1rem",
            }}
          >
            Více o nás
          </Button>
        </Link>
      </section>: 
         <section
        style={{
          padding: "5vh 10vw",
          display: "flex",
          flexDirection: "column",
          gap: "4vh",
          alignItems: "flex-start",
        }}
      >
      <div style={{display: "flex", justifyContent: "space-between",  minHeight: "40vh"}}>
        <div style={{maxWidth: "50%"}}>
            <SubTitle href={"/o-nas"} device={device} label={"O NÁS"}>Kdo jsme</SubTitle>
        <Text sx={{ fontSize: "1rem", lineHeight: "175%", marginTop: "3vh" }}>
          Jsme nadšenci do rychlých aut a inovací. Baví nás rychle jezdit na
          okruhu i si užívat klidné jízdy v příjemném interiéru luxusních aut.
          Chceme tento zážitek poskytnout i vám a proto vám nabízíme naše služby
          na vaší cestě.
        </Text>
        </div>
        <div style={{minWidth: "25%", maxWidth: "30%", display: "flex", flexDirection: "column", alignItems: "center", position: "absolute", right: "10%"}}>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" style={{zIndex: 1}}>
    <path d="M3.41 2H16V0H1a1 1 0 0 0-1 1v16h2V3.41l28.29 28.3 1.41-1.41z" data-name="7-Arrow Up" transform="rotate(90 16 16)" fill="rgb(255, 118, 118, 1)"/>
</svg>
        <div style={{display: "block", position: "absolute", width: "80%", height: "80%",  zIndex: 2, marginTop: "5vh"}}>
       
        <Image src={TeslaBlack} fill style={{objectFit: "cover"}}/>
        </div>
        </div>
      </div>
        <Link href={"/o-nas"}>
          <Button
            size="lg"
            rightIcon="->"
            variant="white"
            sx={{
              paddingLeft: "0",
              color: theme.colors.neutral[7],
              fontWeight: "700",
              fontSize: "1.1rem",
            }}
          >
            Více o nás
          </Button>
        </Link>
      </section>
      }
   
      <section
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "4vh",
          alignItems: "flex-start",
        }}
      >
        <div
          style={{
            padding: "5vh 10vw",
            display: "flex",
            flexDirection: "column",
            gap: "4vh",
          }}
        >
            <SubTitle href={"/sluzby"} device={device} label={"NAŠE SLUŽBY"}>Co nabízíme</SubTitle>
           
          <Text sx={{ fontSize: "1rem", lineHeight: "175%", maxWidth: "60%" }}>
            Pronajímáme Teslu S se kterou se můžete projet na okruhu, zajet si
            kam potřebujete, nebo vás rádi odvezeme
          </Text>
        </div>
        <div style={device !== "l" ? {} : {display: "flex", width: "100%", justifyContent: "space-between", padding: "0 7%"}}>
          {cardContents.map((card) => {
            if(device !== "l"){
              return (
              <Link href={card.link}>
                <div
                  style={{
                    background:
                      "url(" + card.image + ") lightgray 50% / cover no-repeat",
                    height: "25vh",
                    minHeight: "200px",
                    backdropFilter: "saturate(0)",
                    padding: "3vh 6vw",
                    display: "flex",
                    flexDirection: "column",
                  }}
                >
                  <Title
                    order={3}
                    sx={{
                      fontSize: "1.8rem",
                      color: theme.colors.neutral[0],
                      fontWeight: "600",
                    }}
                  >
                    {card.name}
                  </Title>
                  <Text
                    sx={{
                      color: theme.colors.neutral[0],
                      maxWidth: "70%",
                      marginTop: "auto",
                    }}
                  >
                    {card.description}
                  </Text>
                  <Divider
                    sx={{
                      marginTop: "3vh",
                      width: "90vw",
                      filter: "saturate(1)",
                    }}
                    size={"xl"}
                    color={card.color}
                  />
                </div>
              </Link>
            );

            }
            else{
              return (
              <Link href={card.link} style={{width: "24%", borderRadius: "0 0 12px 0" }}>
                <Card
                  sx={{
                    borderRadius: "0 0 12px 0",
                    background:
                      "url(" + card.image + ") lightgray 50% / cover no-repeat",
                    height: "40vh",
                    minHeight: "200px",
                    backdropFilter: "saturate(0)",
                    padding: "",
                    display: "flex",
                    flexDirection: "column",
                    transition: "all 0.5s ease-in-out",
                    ":hover": {
                    backgroundPosition: card.name == "Zážitkové jízdy" ? "right" : "50% 100%",
                    
                    }
                  }}
                >
                  <Title
                    order={3}
                    align="left"
                    sx={{
                      fontSize: "3rem",
                      color: theme.colors.neutral[0],
                      fontWeight: "600",
                      margin: "3vh 2vw"
                    }}
                  >
                    {card.name}
                  </Title>
                  <Card.Section sx={{backgroundColor:  hexToRGBA(card.color, 0.5), marginTop: "auto",  display: "flex", justifyContent: "space-between", alignItems: "center", minHeight: "25%"}}>
                  <Text
                    sx={{
                      color: theme.colors.neutral[0],
                      maxWidth: "70%",
                      padding: "2vh 1vw",
                    }}
                  >
                    {card.description}
                  </Text>
                  <Link style={{maxWidth: "30%", backgroundColor: card.color, padding: "2vh", height: "100%", display: "flex", alignItems: "center"}} href={card.link}><BsArrowUpRight fontWeight={700} fontSize={"2.5rem"} color="#fff" /></Link>
                  </Card.Section>
                
               
                </Card>
              </Link>
            );
            }
          })}
        </div>
        <Link href={"/sluzby"}>
          <Button
            size="lg"
            rightIcon="->"
            variant="white"
            sx={{
              color: theme.colors.neutral[7],
              fontWeight: "700",
              fontSize: "1.1rem",
              marginLeft: device !== "l" ? "" : "8.5vw",
            }}
          >
            Všechny naše služby
          </Button>
        </Link>
      </section>
      <OurTesla slides={slides} />
   
    <OurCustomers articles={main?.attributes?.articles} />
   
        <section
         style={{
          padding: device == "m" ? "5vh 0 5vh 10vw" : "5vh 10vw 5vh 10vw",
          display: "flex",
          flexDirection: "column",
          gap: "4vh",
        }}
        >
         <SubTitle href={"/blog"} device={device} label={"BLOG"}>Nové příspěvky</SubTitle>

        <Blog4Index blog={blog} device={device} />
        <Link href={"/o-nas"}>
          <Button
            size="lg"
            rightIcon="->"
            variant="white"
            sx={{
              color: theme.colors.neutral[7],
              fontWeight: "700",
              fontSize: "1.1rem",
              marginBottom: "0",
              paddingLeft: "0",
            }}
          >
            další příspěvky
          </Button>
        </Link>
        </section>
 
        {device !== "l" &&  <section
        style={{
          padding: "5vh 10vw",
          display: "flex",
          flexDirection: "column",
          gap: "4vh",
        }}
      >
        <Link href={"/o-nas"} style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
        <SubTitle href={"/o-nas"} device={device} label={"VÍCE"}>O nás</SubTitle>
        <svg xmlns="http://www.w3.org/2000/svg" width="122" height="23" viewBox="0 0 122 23" fill="none">
  <path d="M121.061 12.5607C121.646 11.9749 121.646 11.0251 121.061 10.4393L111.515 0.893398C110.929 0.307612 109.979 0.307612 109.393 0.893398C108.808 1.47918 108.808 2.42893 109.393 3.01472L117.879 11.5L109.393 19.9853C108.808 20.5711 108.808 21.5208 109.393 22.1066C109.979 22.6924 110.929 22.6924 111.515 22.1066L121.061 12.5607ZM0 13H120V10H0V13Z" fill="#CDE441"/>
</svg>

        </Link>
        <Link href={"/sluzby"} style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
        <SubTitle href={"/sluzby"} device={device} label={"NAŠE"}>Služby</SubTitle>
        <svg xmlns="http://www.w3.org/2000/svg" width="122" height="23" viewBox="0 0 122 23" fill="none">
  <path d="M121.061 12.5607C121.646 11.9749 121.646 11.0251 121.061 10.4393L111.515 0.893398C110.929 0.307612 109.979 0.307612 109.393 0.893398C108.808 1.47918 108.808 2.42893 109.393 3.01472L117.879 11.5L109.393 19.9853C108.808 20.5711 108.808 21.5208 109.393 22.1066C109.979 22.6924 110.929 22.6924 111.515 22.1066L121.061 12.5607ZM0 13H120V10H0V13Z" fill="#41E4CC"/>
</svg>

        </Link>
        <Link href={"/blog"} style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
        <SubTitle href={"/blog"} device={device} label={"DALŠÍ PŘÍSPĚVKY"}>Blog</SubTitle>
        <svg xmlns="http://www.w3.org/2000/svg" width="122" height="23" viewBox="0 0 122 23" fill="none">
  <path d="M121.061 12.5607C121.646 11.9749 121.646 11.0251 121.061 10.4393L111.515 0.893398C110.929 0.307612 109.979 0.307612 109.393 0.893398C108.808 1.47918 108.808 2.42893 109.393 3.01472L117.879 11.5L109.393 19.9853C108.808 20.5711 108.808 21.5208 109.393 22.1066C109.979 22.6924 110.929 22.6924 111.515 22.1066L121.061 12.5607ZM0 13H120V10H0V13Z" fill="#41BDE4"/>
</svg>

        </Link>
        <Link href={"/kontakt"} style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
        <SubTitle href={"/kontakt"} device={device} label={"OZVĚTE SE NÁM"}>Kontakt</SubTitle>
        <svg xmlns="http://www.w3.org/2000/svg" width="122" height="23" viewBox="0 0 122 23" fill="none">
  <path d="M121.061 12.5607C121.646 11.9749 121.646 11.0251 121.061 10.4393L111.515 0.893398C110.929 0.307612 109.979 0.307612 109.393 0.893398C108.808 1.47918 108.808 2.42893 109.393 3.01472L117.879 11.5L109.393 19.9853C108.808 20.5711 108.808 21.5208 109.393 22.1066C109.979 22.6924 110.929 22.6924 111.515 22.1066L121.061 12.5607ZM0 13H120V10H0V13Z" fill="#4152E4"/>
</svg>

        </Link>
      </section>}
    </>
  );
}


export async function getStaticProps() {

   // recenze
   let fetched2 = await fetch("http://38.242.151.80:1336/api/blogs?populate=deep", {
    headers: {
        Authorization: "Bearer " + process.env.NEXT_PUBLIC_STRAPI_JWT,
    }
    })
    var blog = await fetched2.json()
    blog = blog?.data

    var main = await fetch("http://38.242.151.80:1336/api/main-stranka?populate=deep", {
      headers: {
          Authorization: "Bearer " + process.env.NEXT_PUBLIC_STRAPI_JWT,
      }
      })
      main = await main.json()
      main = main?.data
       

        return ({
        props: {
         blog,
         main,
         
        },
        revalidate: 60,
    })
  }